# Generated by Django 5.2.5 on 2025-09-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoe', 'Sepatu'), ('pants', 'Celana'), ('shirt', 'Kaos / Training Top'), ('outer', 'Jaket / Hoodie'), ('socks', 'Kaos Kaki'), ('bag', 'Tas Olahraga'), ('equipment', 'Perlengkapan (bola, raket, dll)'), ('accessory', 'Aksesori (topi, wristband, dll)'), ('protection', 'Pelindung (shin guard, dll)')], default='update', max_length=20),
        ),
    ]
